type PdfDoc = InstanceType<typeof import("jspdf").jsPDF>;

type SectionToolId = "study-guide" | "learning-path" | "concept-explainer" | "request-match";

type QuizQuestion = {
  question: string;
  options: string[];
  answer: string;
  explanation: string;
};

type FlashcardItem = {
  front: string;
  back: string;
  hint?: string;
};

type StructuredSection = {
  heading: string;
  body: string | string[];
};

type StructuredAiResult =
  | {
      kind: "quiz";
      title: string;
      topic: string;
      questions: QuizQuestion[];
    }
  | {
      kind: "flashcards";
      title: string;
      topic: string;
      cards: FlashcardItem[];
    }
  | {
      kind: SectionToolId;
      title: string;
      topic: string;
      sections: StructuredSection[];
      keyTakeaways?: string[];
    };

type ExportableAiResult = {
  text: string;
  tool: string;
  topic: string;
  source: string;
  structured?: StructuredAiResult;
};

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN = 48;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function filenameSafe(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

function addWrappedText(
  doc: PdfDoc,
  text: string,
  x: number,
  y: number,
  options?: { size?: number },
) {
  doc.setFontSize(options?.size ?? 10);
  const lines = doc.splitTextToSize(text, CONTENT_WIDTH - (x - MARGIN));
  let cursorY = y;

  for (const line of lines) {
    if (cursorY > PAGE_HEIGHT - MARGIN) {
      doc.addPage();
      cursorY = MARGIN;
    }
    doc.text(line, x, cursorY);
    cursorY += (options?.size ?? 10) + 5;
  }

  return cursorY;
}

function addHeading(doc: PdfDoc, text: string, y: number, size = 14) {
  if (y > PAGE_HEIGHT - MARGIN - 24) {
    doc.addPage();
    y = MARGIN;
  }
  doc.setFont("helvetica", "bold");
  doc.setFontSize(size);
  doc.text(text, MARGIN, y);
  doc.setFont("helvetica", "normal");
  return y + size + 10;
}

function addList(doc: PdfDoc, items: string[], y: number) {
  let cursorY = y;
  items.forEach((item) => {
    cursorY = addWrappedText(doc, `• ${item}`, MARGIN + 10, cursorY, { size: 10 }) + 2;
  });
  return cursorY;
}

function addHeader(doc: PdfDoc, result: ExportableAiResult) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(result.structured?.title || "Freducation AI Result", MARGIN, MARGIN);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Topic: ${result.topic}`, MARGIN, MARGIN + 22);
  doc.text(`Generated by: ${result.source}`, MARGIN, MARGIN + 38);

  doc.setDrawColor(210, 210, 210);
  doc.line(MARGIN, MARGIN + 52, PAGE_WIDTH - MARGIN, MARGIN + 52);
  return MARGIN + 76;
}

function addStructuredResult(doc: PdfDoc, result: StructuredAiResult, startY: number) {
  let y = startY;

  if (result.kind === "quiz") {
    y = addHeading(doc, "Questions", y);
    result.questions.forEach((question, index) => {
      y = addWrappedText(doc, `${index + 1}. ${question.question}`, MARGIN, y, { size: 11 }) + 4;
      question.options.forEach((option, optionIndex) => {
        y = addWrappedText(
          doc,
          `${String.fromCharCode(65 + optionIndex)}. ${option}`,
          MARGIN + 14,
          y,
          {
            size: 10,
          },
        );
      });
      y += 8;
    });

    y = addHeading(doc, "Answer Key & Explanations", y + 8);
    result.questions.forEach((question, index) => {
      y = addWrappedText(doc, `${index + 1}. Answer: ${question.answer}`, MARGIN, y, { size: 10 });
      y =
        addWrappedText(doc, `Explanation: ${question.explanation}`, MARGIN + 14, y, { size: 10 }) +
        8;
    });
    return;
  }

  if (result.kind === "flashcards") {
    y = addHeading(doc, "Flashcards", y);
    result.cards.forEach((card, index) => {
      y = addWrappedText(doc, `${index + 1}. ${card.front}`, MARGIN, y, { size: 11 });
      y = addWrappedText(doc, `Answer: ${card.back}`, MARGIN + 14, y, { size: 10 });
      if (card.hint) y = addWrappedText(doc, `Hint: ${card.hint}`, MARGIN + 14, y, { size: 10 });
      y += 8;
    });
    return;
  }

  result.sections.forEach((section) => {
    y = addHeading(doc, section.heading, y);
    if (Array.isArray(section.body)) {
      y = addList(doc, section.body, y) + 6;
    } else {
      y = addWrappedText(doc, section.body, MARGIN, y, { size: 10 }) + 8;
    }
  });

  if (result.keyTakeaways?.length) {
    y = addHeading(doc, "Key Takeaways", y);
    addList(doc, result.keyTakeaways, y);
  }
}

export async function downloadAiResultPdf(result: ExportableAiResult) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const startY = addHeader(doc, result);

  if (result.structured) {
    addStructuredResult(doc, result.structured, startY);
  } else {
    addWrappedText(doc, result.text, MARGIN, startY, { size: 10 });
  }

  const topic = filenameSafe(result.topic || result.tool || "ai-result");
  doc.save(`freducation-${topic || "ai-result"}.pdf`);
}
